Repository codestates-seb/seb41_main_003, pull requests merged in 2023-02, with the labels that each got.

#250 Be/refactor: 특정 프로필 메세지 룸 리스트 조회 쿼리 리팩토링
  server/src/main/java/com/mainproject/server/message/dto/MessageRoomQueryDto.java
  server/src/main/java/com/mainproject/server/message/dto/MessageRoomSimpleResponseDto.java
  server/src/main/java/com/mainproject/server/message/entity/MessageRoom.java
  server/src/main/java/com/mainproject/server/message/repository/MessageRoomRepository.java
  server/src/main/java/com/mainproject/server/message/repository/custom/CustomMessageRoomRepository.java
  server/src/main/java/com/mainproject/server/message/repository/custom/CustomMessageRoomRepositoryImpl.java
  server/src/main/java/com/mainproject/server/message/service/MessageService.java
  server/src/main/java/com/mainproject/server/utils/ResponseStubData.java
  server/src/test/java/com/mainproject/server/message/MessageServiceTest.java
Labels: refactor

#256 Be/refactor: 매칭 요청 취소, 문의 취소 유효성 검증 추가 및 변경
  server/src/main/java/com/mainproject/server/message/service/MessageService.java
  server/src/main/java/com/mainproject/server/tutoring/service/TutoringService.java
Labels: refactor

#258 feat: 모바일 뷰포트 수정
  client/src/components/Button.jsx
  client/src/components/Button.module.css
  client/src/components/MainSection/UserInfoForm.jsx
  client/src/components/MainSection/UserInfoForm.module.css
  client/src/components/profileSection/MyProfileCard.jsx
  client/src/components/profileSection/MyProfileCard.module.css
  client/src/components/profileSection/ProfileCard.jsx
  client/src/components/profileSection/ProfileCard.module.css
  client/src/components/profileSection/ProfileContents.module.css
  client/src/components/profileSection/Toggle.module.css
  client/src/pages/Admin.module.css
  client/src/pages/MyProfile.module.css
  client/src/pages/TuteeProfile.module.css
  client/src/pages/TutorProfile.module.css
  client/src/pages/UserInfo.module.css
Labels: feat

#259 Fe/feat mobile mk
  client/src/components/modal/AdminModal.jsx
  client/src/components/modal/AdminModal.module.css
  client/src/components/modal/DefaultModal.module.css
  client/src/components/modal/ImgLoadModal.module.css
  client/src/components/modal/ReviewDetail.module.css
  client/src/components/modal/ReviewModal.module.css
  client/src/util/StarRating.module.css
Labels: refactor, feat

#260 Fe/feat mobile login
  client/src/components/MainSection/LoginForm.module.css
  client/src/components/MainSection/SignUpForm.module.css
  client/src/components/Tutoring/Journals.jsx
  client/src/components/TutoringList/Tutoring.jsx
  client/src/components/TutoringList/Tutoring.module.css
  client/src/pages/FeedList.module.css
  client/src/pages/TutoringList.jsx
  client/src/pages/TutoringList.module.css
Labels: fix, feat

#261 Merge branch 'main' into dev
  README.md
  client/src/components/Button.jsx
  client/src/components/Button.module.css
  client/src/components/MainSection/FeedItem.jsx
  client/src/components/MainSection/FeedItem.module.css
  client/src/components/MainSection/FilterButton.jsx
  client/src/components/MainSection/FilterDropdown.module.css
  client/src/components/MainSection/LoginForm.module.css
  client/src/components/MainSection/SignUpForm.module.css
  client/src/components/MainSection/UserInfoForm.jsx
  client/src/components/MainSection/UserInfoForm.module.css
  client/src/components/Message/Chat.jsx
  client/src/components/Subject.module.css
  client/src/components/Tutoring/Journals.jsx
  client/src/components/TutoringList/Tutoring.jsx
  client/src/components/TutoringList/Tutoring.module.css
  client/src/components/modal/AdminModal.jsx
  client/src/components/modal/AdminModal.module.css
  client/src/components/modal/DefaultModal.module.css
  client/src/components/modal/ImgLoadModal.module.css
  client/src/components/modal/ReviewDetail.module.css
  client/src/components/modal/ReviewModal.module.css
  client/src/components/profileSection/MyProfileCard.jsx
  client/src/components/profileSection/MyProfileCard.module.css
  client/src/components/profileSection/ProfileCard.jsx
  client/src/components/profileSection/ProfileCard.module.css
  client/src/components/profileSection/ProfileContents.module.css
  client/src/components/profileSection/Toggle.module.css
  client/src/pages/Admin.module.css
  client/src/pages/FeedList.module.css
  client/src/pages/MyProfile.module.css
  client/src/pages/TuteeList.jsx
  client/src/pages/TuteeProfile.module.css
  client/src/pages/TutorList.jsx
  client/src/pages/TutorList.module.css
  client/src/pages/TutorProfile.module.css
  client/src/pages/TutoringList.jsx
  client/src/pages/TutoringList.module.css
  client/src/pages/UserInfo.module.css
  client/src/util/StarRating.module.css
  server/src/main/java/com/mainproject/server/message/service/MessageService.java
  server/src/main/java/com/mainproject/server/tutoring/service/TutoringService.java
Labels: fix, feat

#263 Be/refactor: 과외 상세 조회 쿼리 성능 개선
  server/src/main/java/com/mainproject/server/tutoring/repository/custom/CustomTutoringRepository.java
  server/src/main/java/com/mainproject/server/tutoring/repository/custom/CustomTutoringRepositoryImpl.java
  server/src/main/java/com/mainproject/server/tutoring/service/TutoringService.java
  server/src/test/java/com/mainproject/server/tutoring/service/TutoringServiceTest.java
Labels: refactor

#264 fix: 수정사항 및 트러블슈팅 반영
  client/src/components/JournalSection/EditJournalForm.jsx
  client/src/components/MainSection/FilterDropdown.module.css
  client/src/components/MainSection/LoginForm.module.css
  client/src/components/TutoringList/Tutoring.jsx
  client/src/components/TutoringList/Tutoring.module.css
  client/src/components/modal/DefaultModal.module.css
  client/src/pages/FeedList.module.css
  client/src/pages/TuteeList.jsx
  client/src/pages/TutorList.jsx
  client/src/pages/TutoringList.jsx
  client/src/pages/TutoringList.module.css
  server/src/main/java/com/mainproject/server/tutoring/repository/custom/CustomTutoringRepository.java
  server/src/main/java/com/mainproject/server/tutoring/repository/custom/CustomTutoringRepositoryImpl.java
  server/src/main/java/com/mainproject/server/tutoring/service/TutoringService.java
  server/src/test/java/com/mainproject/server/tutoring/service/TutoringServiceTest.java
Labels: fix, feat

#265 Fe/feat mobile mk
  client/src/components/Tutoring/FinishedJournalList.jsx
  client/src/components/Tutoring/FinishedJournalList.module.css
  client/src/components/Tutoring/JournalList.jsx
  client/src/components/Tutoring/JournalList.module.css
  client/src/components/Tutoring/Journals.jsx
  client/src/pages/Tutoring.module.css
Labels: refactor, feat

#266 feat: 모바일 뷰포트 적용 (Message, Add/EditJournal)
  client/src/components/Header.module.css
  client/src/components/JournalSection/DatePickerForm.module.css
  client/src/components/JournalSection/EditJournalForm.jsx
  client/src/components/JournalSection/EditJournalForm.module.css
  client/src/components/Message/Chat.module.css
  client/src/components/Message/MessageContent.jsx
  client/src/components/Message/MessageContent.module.css
  client/src/components/Message/MessageList.jsx
  client/src/components/Message/MessageList.module.css
  client/src/pages/ChangeJournal.module.css
  client/src/pages/FeedList.module.css
  client/src/pages/Message.jsx
  client/src/pages/Message.module.css
Labels: fix, feat

#267 feat: Scroll Restoration
  client/src/App.jsx
  client/src/util/ScrollToTop.jsx
Labels: feat

#268 fix: JournalList 모바일 뷰포트 개선 #257
  client/src/components/Tutoring/JournalList.module.css
  client/src/components/Tutoring/Journals.jsx
  client/src/pages/Tutoring.module.css
Labels: fix

#269 Fe/feat mobile mk
  client/src/components/MainSection/FilterDropdown.module.css
  client/src/pages/FeedList.module.css
Labels: feat

#270 Fe/feat mobile ym
  client/src/components/Input.module.css
  client/src/components/JournalSection/JournalForm.jsx
  client/src/components/JournalSection/JournalForm.module.css
  client/src/pages/ChangeProfile.module.css
  client/src/pages/Journal.module.css
Labels: feat

#272 FE/Feat : Responsive Web
  client/src/App.jsx
  client/src/components/ChangeProfile/ChangeProfileCard.jsx
  client/src/components/ChangeProfile/ChangeProfileCard.module.css
  client/src/components/ChangeProfile/ChangeProfileContents.module.css
  client/src/components/Header.module.css
  client/src/components/Input.module.css
  client/src/components/JournalSection/DatePickerForm.module.css
  client/src/components/JournalSection/EditJournalForm.jsx
  client/src/components/JournalSection/EditJournalForm.module.css
  client/src/components/JournalSection/JournalForm.jsx
  client/src/components/JournalSection/JournalForm.module.css
  client/src/components/MainSection/FilterDropdown.module.css
  client/src/components/MainSection/SignUpForm.jsx
  client/src/components/Message/Chat.module.css
  client/src/components/Message/MessageContent.jsx
  client/src/components/Message/MessageContent.module.css
  client/src/components/Message/MessageList.jsx
  client/src/components/Message/MessageList.module.css
  client/src/components/Tutoring/FinishedJournalList.jsx
  client/src/components/Tutoring/FinishedJournalList.module.css
  client/src/components/Tutoring/JournalList.jsx
  client/src/components/Tutoring/JournalList.module.css
  client/src/components/Tutoring/Journals.jsx
  client/src/pages/ChangeJournal.module.css
  client/src/pages/ChangeProfile.module.css
  client/src/pages/FeedList.module.css
  client/src/pages/Journal.module.css
  client/src/pages/Message.jsx
  client/src/pages/Message.module.css
  client/src/pages/Tutoring.module.css
  client/src/util/ScrollToTop.jsx
Labels: fix, feat

#273 BE/Refactor: Websocket Message 구현
  server/build.gradle
  server/src/main/java/com/mainproject/server/alarm/entity/Alarm.java
  server/src/main/java/com/mainproject/server/auth/filter/CorsFilter.java
  server/src/main/java/com/mainproject/server/auth/token/JwtTokenizer.java
  server/src/main/java/com/mainproject/server/config/RedisConfig.java
  server/src/main/java/com/mainproject/server/config/SecurityConfig.java
  server/src/main/java/com/mainproject/server/config/WebSocketConfig.java
  server/src/main/java/com/mainproject/server/config/handler/WebSocketHandler.java
  server/src/main/java/com/mainproject/server/message/controller/MessageController.java
  server/src/main/java/com/mainproject/server/message/dto/MessageResponseDto.java
  server/src/main/java/com/mainproject/server/message/service/MessageService.java
  server/src/main/java/com/mainproject/server/message/ui/RedisPublisher.java
  server/src/main/java/com/mainproject/server/message/ui/RedisSubscriber.java
  server/src/main/java/com/mainproject/server/utils/ResponseStubData.java
  server/src/test/java/com/mainproject/server/message/controller/MessageControllerTest.java
Labels: refactor

#274 FE/feat: 실시간 채팅 구현
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/Message/Chat.jsx
  client/src/components/Message/MessageContent.jsx
  client/src/components/Message/MessageList.jsx
  client/src/pages/Message.jsx
  client/src/util/useLiveChat.js
Labels: fix, feat

#275 feat: 실시간 채팅 구현
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/Message/Chat.jsx
  client/src/components/Message/MessageContent.jsx
  client/src/components/Message/MessageList.jsx
  client/src/pages/Message.jsx
  client/src/util/useLiveChat.js
  server/build.gradle
  server/src/main/java/com/mainproject/server/alarm/entity/Alarm.java
  server/src/main/java/com/mainproject/server/auth/filter/CorsFilter.java
  server/src/main/java/com/mainproject/server/auth/token/JwtTokenizer.java
  server/src/main/java/com/mainproject/server/config/RedisConfig.java
  server/src/main/java/com/mainproject/server/config/SecurityConfig.java
  server/src/main/java/com/mainproject/server/config/WebSocketConfig.java
  server/src/main/java/com/mainproject/server/config/handler/WebSocketHandler.java
  server/src/main/java/com/mainproject/server/message/controller/MessageController.java
  server/src/main/java/com/mainproject/server/message/dto/MessageResponseDto.java
  server/src/main/java/com/mainproject/server/message/service/MessageService.java
  server/src/main/java/com/mainproject/server/message/ui/RedisPublisher.java
  server/src/main/java/com/mainproject/server/message/ui/RedisSubscriber.java
  server/src/main/java/com/mainproject/server/utils/ResponseStubData.java
  server/src/test/java/com/mainproject/server/message/controller/MessageControllerTest.java
Labels: feat

#277 Be/feat 알림 기능 구현
  server/src/main/java/com/mainproject/server/alarm/controller/AlarmController.java
  server/src/main/java/com/mainproject/server/alarm/dto/AlarmDto.java
  server/src/main/java/com/mainproject/server/alarm/entity/Alarm.java
  server/src/main/java/com/mainproject/server/alarm/repository/AlarmRepository.java
  server/src/main/java/com/mainproject/server/alarm/service/AlarmService.java
  server/src/main/java/com/mainproject/server/constant/AlarmStatus.java
  server/src/main/java/com/mainproject/server/constant/AlarmType.java
  server/src/main/java/com/mainproject/server/constant/ErrorCode.java
  server/src/main/java/com/mainproject/server/dateNotice/service/DateNoticeService.java
  server/src/main/java/com/mainproject/server/message/service/MessageService.java
  server/src/main/java/com/mainproject/server/profile/entity/Profile.java
  server/src/main/java/com/mainproject/server/review/service/ReviewService.java
  server/src/main/java/com/mainproject/server/tutoring/service/TutoringService.java
Labels: feat

#278 test: Alarm 기능 추가 Test 코드 반영
  server/src/test/java/com/mainproject/server/tutoring/service/TutoringServiceTest.java
Labels: test

#279 fix: Alarm Enum 필드 String 타입으로 수정
  server/src/main/java/com/mainproject/server/alarm/entity/Alarm.java
Labels: fix

#280 Be/fix 알림 기능 에러 및 오타 수정
  server/src/main/java/com/mainproject/server/alarm/controller/AlarmController.java
  server/src/main/java/com/mainproject/server/alarm/service/AlarmService.java
Labels: fix

#281 FE / fix: message 관련 오류 및 이슈 해결
  client/src/components/Message/Chat.module.css
  client/src/components/Message/MessageContent.jsx
  client/src/components/Message/MessageContent.module.css
  client/src/components/Message/MessageList.module.css
  client/src/pages/Message.module.css
  client/src/util/useLiveChat.js
Labels: fix

#282 FE / fix: 모바일 뷰포트 추가 이슈 해결
  client/src/components/Message/MessageContent.jsx
  client/src/components/Message/MessageContent.module.css
Labels: fix

#283 fix: useEffect 종속성 배열 변경
  .github/workflows/client_deploy.yml
  client/src/components/Message/MessageContent.jsx
Labels: fix

#284 chore: Message Room 조회 정렬 변경
  server/src/main/java/com/mainproject/server/message/controller/MessageController.java
Labels: fix

#286 FE / feat: 알림 확인 API 연결
  client/src/components/Header.jsx
  client/src/components/Header.module.css
  client/src/components/NoticeItem.jsx
  client/src/components/NoticeItem.module.css
  client/src/components/NotificationBox.jsx
  client/src/components/NotificationBox.module.css
  client/src/recoil/profile.js
Labels: fix, feat

#287 Fe/feat: 알림 전체 조회, 확인, 삭제 API 연결
  client/src/components/Header.jsx
  client/src/components/NoticeItem.jsx
  client/src/components/NoticeItem.module.css
  client/src/components/NotificationBox.jsx
  client/src/components/NotificationBox.module.css
Labels: feat

#288 feat: 알림 기능 구현
  .github/workflows/client_deploy.yml
  client/src/components/Header.jsx
  client/src/components/Header.module.css
  client/src/components/Message/Chat.module.css
  client/src/components/Message/MessageContent.jsx
  client/src/components/Message/MessageContent.module.css
  client/src/components/Message/MessageList.module.css
  client/src/components/NoticeItem.jsx
  client/src/components/NoticeItem.module.css
  client/src/components/NotificationBox.jsx
  client/src/components/NotificationBox.module.css
  client/src/pages/Message.module.css
  client/src/recoil/profile.js
  client/src/util/useLiveChat.js
  server/src/main/java/com/mainproject/server/alarm/controller/AlarmController.java
  server/src/main/java/com/mainproject/server/alarm/dto/AlarmDto.java
  server/src/main/java/com/mainproject/server/alarm/entity/Alarm.java
  server/src/main/java/com/mainproject/server/alarm/repository/AlarmRepository.java
  server/src/main/java/com/mainproject/server/alarm/service/AlarmService.java
  server/src/main/java/com/mainproject/server/constant/AlarmStatus.java
  server/src/main/java/com/mainproject/server/constant/AlarmType.java
  server/src/main/java/com/mainproject/server/constant/ErrorCode.java
  server/src/main/java/com/mainproject/server/dateNotice/service/DateNoticeService.java
  server/src/main/java/com/mainproject/server/message/controller/MessageController.java
  server/src/main/java/com/mainproject/server/message/service/MessageService.java
  server/src/main/java/com/mainproject/server/profile/entity/Profile.java
  server/src/main/java/com/mainproject/server/review/service/ReviewService.java
  server/src/main/java/com/mainproject/server/tutoring/service/TutoringService.java
  server/src/test/java/com/mainproject/server/tutoring/service/TutoringServiceTest.java
Labels: fix, feat

#289 FE / feat: PWA 설정 및 오프라인 핸들링 추가
  client/package-lock.json
  client/package.json
  client/public/manifest.json
  client/src/App.jsx
  client/src/components/Offline.jsx
  client/src/components/Offline.module.css
  client/src/index.jsx
  client/src/service-worker.js
  client/src/serviceWorkerRegistration.js
Labels: feat
