Repository codestates-seb/seb41_main_003, pull requests merged in 2023-01, with the labels that each got.

#11 feat: 기본 레이아웃 설정 및 페이지 생성
  client/.eslintrc.json
  client/.stylelintrc.json
  client/src/App.css
  client/src/App.js
  client/src/App.jsx
  client/src/assets/defaultUser.png
  client/src/assets/enLogo.svg
  client/src/assets/koLogo.svg
  client/src/assets/logoTest.svg
  client/src/assets/symbol.svg
  client/src/components/Header.jsx
  client/src/default.css
  client/src/index.css
  client/src/index.jsx
  client/src/pages/AddProfile.jsx
  client/src/pages/Admin.jsx
  client/src/pages/EditProfile.jsx
  client/src/pages/Login.jsx
  client/src/pages/Message.jsx
  client/src/pages/MyProfile.jsx
  client/src/pages/SignUp.jsx
  client/src/pages/TestPage.jsx
  client/src/pages/TuteeList.jsx
  client/src/pages/TuteeProfile.jsx
  client/src/pages/TutorList.jsx
  client/src/pages/TutorProfile.jsx
  client/src/pages/Tutoring.jsx
  client/src/pages/TutoringList.jsx
  client/src/pages/UserInfo.jsx
Labels: feat

#12 BE: DTO 전체 검토 및 오타 수정
  server/src/main/java/com/mainproject/server/dateNotice/dto/DateNoticePatchDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/DateNoticePostDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/DateNoticeResponseDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/HomeworkPatchDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/HomeworkResponseDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/NoticePatchDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/NoticeResponseDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/SchedulePatchDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/ScheduleResponseDto.java
  server/src/main/java/com/mainproject/server/dateNotice/entity/DateNotice.java
  server/src/main/java/com/mainproject/server/dateNotice/entity/Notice.java
  server/src/main/java/com/mainproject/server/dateNotice/entity/Schedule.java
  server/src/main/java/com/mainproject/server/review/dto/ReviewPatchDto.java
  server/src/main/java/com/mainproject/server/review/dto/ReviewPostDto.java
  server/src/main/java/com/mainproject/server/review/dto/ReviewResponseDto.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringPatchDto.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringPostDto.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringResponseDto.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringSimpleResponseDto.java
  server/src/main/java/com/mainproject/server/tutoring/entity/Tutoring.java
Labels: feat

#13 feat: Response Dto Stub Data 작성
  server/src/main/java/com/mainproject/server/dateNotice/dto/DateNoticeResponseDto.java
  server/src/main/java/com/mainproject/server/message/dto/MessageRoomSimpleResponseDto.java
  server/src/main/java/com/mainproject/server/review/dto/ReviewResponseDto.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringResponseDto.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringSimpleResponseDto.java
  server/src/main/java/com/mainproject/server/utils/StubData.java
Labels: feat

#15 chore: Profile Status Tutor 추가
  server/src/main/java/com/mainproject/server/constant/ProfileStatus.java
Labels: fix

#16 feat:MessageController 작성
  server/src/main/java/com/mainproject/server/message/controller/MessageController.java
Labels: feat

#17 Be/feat tutoring, review controller
  server/src/main/java/com/mainproject/server/review/controller/ReviewController.java
  server/src/main/java/com/mainproject/server/tutoring/controller/TutoringController.java
Labels: feat

#20 BE: feat User,Profile,Image Stub Controller
  server/src/main/java/com/mainproject/server/dateNotice/entity/DateNotice.java
  server/src/main/java/com/mainproject/server/dto/PageResponseDto.java
  server/src/main/java/com/mainproject/server/dto/ResponseDto.java
  server/src/main/java/com/mainproject/server/image/controller/ImageController.java
  server/src/main/java/com/mainproject/server/message/entity/Message.java
  server/src/main/java/com/mainproject/server/profile/controller/ProfileController.java
  server/src/main/java/com/mainproject/server/profile/dto/ProfileResponseDto.java
  server/src/main/java/com/mainproject/server/user/controller/UserController.java
  server/src/main/java/com/mainproject/server/utils/StubData.java
Labels: feat

#22 BE: feat 디스코드 Server Error 로깅을 위한 WebHook 로직 작성
  server/src/main/java/com/mainproject/server/home/HomeController.java
  server/src/main/java/com/mainproject/server/user/controller/UserController.java
  server/src/main/java/com/mainproject/server/webhook/WebHookDto.java
  server/src/main/java/com/mainproject/server/webhook/WebHookService.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application.yml
Labels: feat

#27 chore: controller dto 추가
  server/src/main/java/com/mainproject/server/dateNotice/dto/DateNoticePatchDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/DateNoticePostDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/HomeworkDto.java
  server/src/main/java/com/mainproject/server/review/controller/ReviewController.java
Labels: todo

#29 BE: Sutb Controller 리팩토링
  server/src/main/java/com/mainproject/server/dateNotice/controller/DateNoticeController.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/DateNoticeSimpleResponseDto.java
  server/src/main/java/com/mainproject/server/dto/PageResponseDto.java
  server/src/main/java/com/mainproject/server/image/controller/ImageController.java
  server/src/main/java/com/mainproject/server/message/controller/MessageController.java
  server/src/main/java/com/mainproject/server/profile/controller/ProfileController.java
  server/src/main/java/com/mainproject/server/profile/dto/ProfileListResponseDto.java
  server/src/main/java/com/mainproject/server/profile/dto/ProfilePageDto.java
  server/src/main/java/com/mainproject/server/profile/dto/ProfileResponseDto.java
  server/src/main/java/com/mainproject/server/profile/dto/ProfileSimpleResponseDto.java
  server/src/main/java/com/mainproject/server/tutoring/controller/TutoringController.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringDto.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringPatchDto.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringResponseDto.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringSimpleResponseDto.java
  server/src/main/java/com/mainproject/server/user/controller/UserController.java
  server/src/main/java/com/mainproject/server/utils/StubData.java
Labels: fix

#30 feat: repository 초기 설정
  server/src/main/java/com/mainproject/server/dateNotice/repository/DateNoticeRepository.java
  server/src/main/java/com/mainproject/server/dateNotice/repository/HomeworkRepository.java
  server/src/main/java/com/mainproject/server/dateNotice/repository/NoticeRepository.java
  server/src/main/java/com/mainproject/server/dateNotice/repository/ScheduleRepository.java
  server/src/main/java/com/mainproject/server/image/repository/ImageRepository.java
  server/src/main/java/com/mainproject/server/message/repository/MessageRepository.java
  server/src/main/java/com/mainproject/server/message/repository/MessageRoomRepository.java
  server/src/main/java/com/mainproject/server/profile/repository/ProfileRepository.java
  server/src/main/java/com/mainproject/server/review/repository/ReviewRepository.java
  server/src/main/java/com/mainproject/server/subject/repository/SubjectProfileRepository.java
  server/src/main/java/com/mainproject/server/subject/repository/SubjectRepository.java
  server/src/main/java/com/mainproject/server/tutoring/repository/TutoringRepository.java
  server/src/main/java/com/mainproject/server/user/repository/UserRepository.java
Labels: todo

#31 chore: env , 설정 파일 수정
  server/build.gradle
  server/src/main/java/com/mainproject/server/config/AwsConfig.java
  server/src/main/resources/application-local.yml
Labels: feat

#35 Be/feat/test check
  server/src/main/java/com/mainproject/server/config/AwsConfig.java
  server/src/main/java/com/mainproject/server/webhook/WebHookService.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application.yml
Labels: feat

#38 feat: Global Exception Advice
  .gitignore
  server/src/main/java/com/mainproject/server/advice/ExceptionAdvice.java
  server/src/main/java/com/mainproject/server/constant/ErrorCode.java
  server/src/main/java/com/mainproject/server/dto/ErrorResponse.java
  server/src/main/java/com/mainproject/server/exception/ServiceLogicException.java
  server/src/main/java/com/mainproject/server/home/HomeController.java
  server/src/main/java/com/mainproject/server/user/service/UserService.java
  server/src/main/java/com/mainproject/server/webhook/WebHookService.java
Labels: feat

#41 feat: review 기능 구현
  server/src/main/java/com/mainproject/server/review/service/ReviewService.java
Labels: feat

#47 feat: dateNotice 기능 구현
  server/src/main/java/com/mainproject/server/dateNotice/service/DateNoticeService.java
Labels: feat

#44 feat: JWT & OAuth2 구현
  server/build.gradle
  server/src/main/java/com/mainproject/server/auth/controller/AuthController.java
  server/src/main/java/com/mainproject/server/auth/details/UserCustomDetailsService.java
  server/src/main/java/com/mainproject/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/mainproject/server/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/mainproject/server/auth/handler/UserAccessDeniedHandler.java
  server/src/main/java/com/mainproject/server/auth/handler/UserAuthenticationEntryPoint.java
  server/src/main/java/com/mainproject/server/auth/handler/UserAuthenticationFailureHandler.java
  server/src/main/java/com/mainproject/server/auth/handler/UserAuthenticationSuccessHandler.java
  server/src/main/java/com/mainproject/server/auth/oauth2/attribute/OAuth2Attribute.java
  server/src/main/java/com/mainproject/server/auth/oauth2/provider/CustomOAuth2Provider.java
  server/src/main/java/com/mainproject/server/auth/oauth2/service/CustomOAuth2UserService.java
  server/src/main/java/com/mainproject/server/auth/redis/dto/RefreshDto.java
  server/src/main/java/com/mainproject/server/auth/redis/entity/RefreshEntity.java
  server/src/main/java/com/mainproject/server/auth/redis/repository/RefreshRepository.java
  server/src/main/java/com/mainproject/server/auth/redis/service/RefreshService.java
  server/src/main/java/com/mainproject/server/auth/token/JwtAuthorityUtils.java
  server/src/main/java/com/mainproject/server/auth/token/JwtTokenizer.java
  server/src/main/java/com/mainproject/server/auth/token/Token.java
  server/src/main/java/com/mainproject/server/config/PasswordEncoderConfig.java
  server/src/main/java/com/mainproject/server/config/SecurityConfig.java
  server/src/main/java/com/mainproject/server/dto/AuthSuccessTokenResponseDto.java
  server/src/main/java/com/mainproject/server/user/entity/User.java
  server/src/main/java/com/mainproject/server/user/repository/UserRepository.java
  server/src/main/java/com/mainproject/server/user/service/UserService.java
  server/src/main/java/com/mainproject/server/utils/ErrorResponder.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application.yml
Labels: feat

#48 BE: feat User Service 및 User/Auth Controller 구현
  server/src/main/java/com/mainproject/server/auth/controller/AuthController.java
  server/src/main/java/com/mainproject/server/auth/details/UserCustomDetailsService.java
  server/src/main/java/com/mainproject/server/auth/dto/PasswordDto.java
  server/src/main/java/com/mainproject/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/mainproject/server/auth/handler/UserAuthenticationSuccessHandler.java
  server/src/main/java/com/mainproject/server/auth/oauth2/service/CustomOAuth2UserService.java
  server/src/main/java/com/mainproject/server/auth/token/JwtTokenizer.java
  server/src/main/java/com/mainproject/server/constant/ErrorCode.java
  server/src/main/java/com/mainproject/server/user/controller/UserController.java
  server/src/main/java/com/mainproject/server/user/dto/UserPatchDto.java
  server/src/main/java/com/mainproject/server/user/entity/User.java
  server/src/main/java/com/mainproject/server/user/mapper/UserMapper.java
  server/src/main/java/com/mainproject/server/user/service/UserService.java
  server/src/main/resources/application-local.yml
Labels: feat

#49 Fe/feat main section 구현
  client/src/App.jsx
  client/src/components/Button.module.css
  client/src/components/MainSection/FeedItem.jsx
  client/src/components/MainSection/FeedItem.module.css
  client/src/components/MainSection/FilterDropdown.jsx
  client/src/components/MainSection/FilterDropdown.module.css
  client/src/components/MainSection/LoginForm.jsx
  client/src/components/MainSection/LoginForm.module.css
  client/src/components/MainSection/MenuButton.jsx
  client/src/components/MainSection/MenuButton.module.css
  client/src/components/MainSection/SignUpForm.jsx
  client/src/components/MainSection/SignUpForm.module.css
  client/src/components/MainSection/UserInfoForm.jsx
  client/src/components/MainSection/UserInfoForm.module.css
  client/src/components/Modal.jsx
  client/src/components/Modal.module.css
  client/src/components/Subject.module.css
  client/src/default.css
  client/src/pages/Admin.jsx
  client/src/pages/Admin.module.css
  client/src/pages/Login.jsx
  client/src/pages/Login.module.css
  client/src/pages/SignUp.jsx
  client/src/pages/SignUp.module.css
  client/src/pages/TuteeList.jsx
  client/src/pages/TuteeList.module.css
  client/src/pages/TutorList.jsx
  client/src/pages/TutorList.module.css
  client/src/pages/UserInfo.jsx
  client/src/pages/UserInfo.module.css
Labels: feat

#50 feat: profile section 구현
  client/.prettierrc.json
  client/src/components/Modal.jsx
  client/src/components/profileSection/ProfileCard.jsx
  client/src/components/profileSection/ProfileCard.module.css
  client/src/components/profileSection/ProfileContents.jsx
  client/src/components/profileSection/ProfileContents.module.css
  client/src/components/profileSection/Toggle.jsx
  client/src/components/profileSection/Toggle.module.css
  client/src/components/profileSection/index.jsx
  client/src/pages/MyProfile.jsx
  client/src/pages/MyProfile.module.css
  client/src/pages/TuteeProfile.jsx
  client/src/pages/TuteeProfile.module.css
  client/src/pages/TutorProfile.jsx
  client/src/pages/TutorProfile.module.css
Labels: feat

#53 feat: OAuth2 Success Handler 구현 및 로그인 후 응답 데이터 수정
  server/src/main/java/com/mainproject/server/auth/handler/UserAuthenticationSuccessHandler.java
  server/src/main/java/com/mainproject/server/auth/oauth2/OAuth2UserSuccessHandler.java
  server/src/main/java/com/mainproject/server/auth/oauth2/service/CustomOAuth2UserService.java
  server/src/main/java/com/mainproject/server/config/SecurityConfig.java
  server/src/main/java/com/mainproject/server/constant/ProfileStatus.java
  server/src/main/java/com/mainproject/server/dto/AuthSuccessTokenResponseDto.java
  server/src/main/java/com/mainproject/server/profile/dto/ProfileSimpleResponseDto.java
  server/src/main/java/com/mainproject/server/utils/StubData.java
Labels: feat

#55 Be/feat messsage logic2
  .gitignore
  server/src/main/java/com/mainproject/server/advice/ExceptionAdvice.java
  server/src/main/java/com/mainproject/server/config/AwsConfig.java
  server/src/main/java/com/mainproject/server/constant/ErrorCode.java
  server/src/main/java/com/mainproject/server/dateNotice/service/DateNoticeService.java
  server/src/main/java/com/mainproject/server/dto/ErrorResponse.java
  server/src/main/java/com/mainproject/server/exception/ServiceLogicException.java
  server/src/main/java/com/mainproject/server/home/HomeController.java
  server/src/main/java/com/mainproject/server/message/controller/MessageController.java
  server/src/main/java/com/mainproject/server/message/entity/Message.java
  server/src/main/java/com/mainproject/server/message/repository/MessageRoomRepository.java
  server/src/main/java/com/mainproject/server/message/service/MessageService.java
  server/src/main/java/com/mainproject/server/review/service/ReviewService.java
  server/src/main/java/com/mainproject/server/user/service/UserService.java
  server/src/main/java/com/mainproject/server/webhook/WebHookService.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application.yml
Labels: feat

#62 feat: Message 페이지 생성
  client/src/components/Button.jsx
  client/src/components/Message/Chat.jsx
  client/src/components/Message/MessageContent.jsx
  client/src/components/Message/MessageContent.module.css
  client/src/components/Message/MessageList.jsx
  client/src/components/Message/MessageList.module.css
  client/src/components/Modal.jsx
  client/src/components/Modal.module.css
  client/src/pages/Message.jsx
  client/src/pages/Message.module.css
  client/src/pages/ModalTestPage.jsx
Labels: feat

#63 Be/feat: Profile 서비스 & 컨트롤러 로직 구현
  server/src/main/java/com/mainproject/server/audit/Auditable.java
  server/src/main/java/com/mainproject/server/constant/ErrorCode.java
  server/src/main/java/com/mainproject/server/profile/controller/ProfileController.java
  server/src/main/java/com/mainproject/server/profile/dto/ProfileDto.java
  server/src/main/java/com/mainproject/server/profile/dto/ProfilePageDto.java
  server/src/main/java/com/mainproject/server/profile/dto/WantedDto.java
  server/src/main/java/com/mainproject/server/profile/entity/Profile.java
  server/src/main/java/com/mainproject/server/profile/mapper/ProfileMapper.java
  server/src/main/java/com/mainproject/server/profile/service/ProfileService.java
  server/src/main/java/com/mainproject/server/subject/entity/SubjectProfile.java
  server/src/main/java/com/mainproject/server/subject/repository/SubjectProfileRepository.java
  server/src/main/java/com/mainproject/server/user/dto/UserResponseDto.java
  server/src/main/resources/data.sql
Labels: feat

#65 Be/feat message logic
  server/src/main/java/com/mainproject/server/message/controller/MessageController.java
  server/src/main/java/com/mainproject/server/message/service/MessageService.java
Labels: feat

#66 Be/feat controller
  server/src/main/java/com/mainproject/server/constant/NoticeStatus.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/DateNoticePatchDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/DateNoticePostDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/DateNoticeResponseDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/DateNoticeSimpleResponseDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/HomeworkDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/NoticePatchDto.java
  server/src/main/java/com/mainproject/server/dateNotice/entity/DateNotice.java
  server/src/main/java/com/mainproject/server/dateNotice/entity/Homework.java
  server/src/main/java/com/mainproject/server/dateNotice/mapper/DateNoticeMapper.java
  server/src/main/java/com/mainproject/server/dateNotice/service/DateNoticeService.java
  server/src/main/java/com/mainproject/server/review/controller/ReviewController.java
  server/src/main/java/com/mainproject/server/review/dto/ReviewPatchDto.java
  server/src/main/java/com/mainproject/server/review/dto/ReviewPostDto.java
  server/src/main/java/com/mainproject/server/review/mapper/ReviewMapper.java
  server/src/main/java/com/mainproject/server/review/service/ReviewService.java
  server/src/main/java/com/mainproject/server/tutoring/controller/TutoringController.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringDto.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringPatchDto.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringPostDto.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringResponseDto.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringSimplePatchDto.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringSimpleResponseDto.java
  server/src/main/java/com/mainproject/server/tutoring/entity/Tutoring.java
  server/src/main/java/com/mainproject/server/tutoring/mapper/TutoringMapper.java
  server/src/main/java/com/mainproject/server/tutoring/service/TutoringService.java
Labels: fix, feat

#67 chore: query 수정
  server/src/main/java/com/mainproject/server/tutoring/repository/TutoringRepository.java
  server/src/main/java/com/mainproject/server/tutoring/service/TutoringService.java
Labels: fix

#68 Be/feat Message 서비스 로직 구현
  server/src/main/java/com/mainproject/server/message/controller/MessageController.java
  server/src/main/java/com/mainproject/server/message/dto/MessagePostDto.java
  server/src/main/java/com/mainproject/server/message/dto/MessageResponseDto.java
  server/src/main/java/com/mainproject/server/message/dto/MessageRoomPostDto.java
  server/src/main/java/com/mainproject/server/message/dto/MessageRoomResponseDto.java
  server/src/main/java/com/mainproject/server/message/dto/MessageRoomSimpleResponseDto.java
  server/src/main/java/com/mainproject/server/message/entity/Message.java
  server/src/main/java/com/mainproject/server/message/entity/MessageRoom.java
  server/src/main/java/com/mainproject/server/message/mapper/MessageMapper.java
  server/src/main/java/com/mainproject/server/message/repository/MessageRoomRepository.java
  server/src/main/java/com/mainproject/server/message/service/MessageService.java
  server/src/main/java/com/mainproject/server/utils/StubData.java
Labels: feat

#71 Be/edit dto
  server/src/main/java/com/mainproject/server/config/SecurityConfig.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/DateNoticePatchDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/SchedulePatchDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/ScheduleResponseDto.java
  server/src/main/java/com/mainproject/server/review/dto/ReviewPatchDto.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringDto.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringPatchDto.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringPostDto.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringSimplePatchDto.java
Labels: fix

#70 feat: TutorlingList 페이지 작성
  client/src/components/Header.jsx
  client/src/components/TutoringList/Tutoring.jsx
  client/src/components/TutoringList/Tutoring.module.css
  client/src/pages/TutoringList.jsx
  client/src/pages/TutoringList.module.css
Labels: feat

#74 Be/feat tutoring service
  server/src/main/java/com/mainproject/server/dateNotice/dto/DateNoticePatchDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/DateNoticePostDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/DateNoticeResponseDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/HomeworkPatchDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/HomeworkPostDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/HomeworkResponseDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/NoticePatchDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/NoticeResponseDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/ScheduleResponseDto.java
  server/src/main/java/com/mainproject/server/dateNotice/mapper/DateNoticeMapper.java
  server/src/main/java/com/mainproject/server/dateNotice/repository/HomeworkRepository.java
  server/src/main/java/com/mainproject/server/dateNotice/repository/NoticeRepository.java
  server/src/main/java/com/mainproject/server/dateNotice/repository/ScheduleRepository.java
  server/src/main/java/com/mainproject/server/dateNotice/service/DateNoticeService.java
  server/src/main/java/com/mainproject/server/message/entity/MessageRoom.java
  server/src/main/java/com/mainproject/server/message/service/MessageService.java
  server/src/main/java/com/mainproject/server/review/dto/ReviewResponseDto.java
  server/src/main/java/com/mainproject/server/review/service/ReviewService.java
  server/src/main/java/com/mainproject/server/tutoring/controller/TutoringController.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringDto.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringPostDto.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringResponseDto.java
  server/src/main/java/com/mainproject/server/tutoring/entity/Tutoring.java
  server/src/main/java/com/mainproject/server/tutoring/mapper/TutoringMapper.java
  server/src/main/java/com/mainproject/server/tutoring/service/TutoringService.java
  server/src/main/java/com/mainproject/server/utils/StubData.java
Labels: fix, feat

#73 feat: Tutor, Tutee 전체 프로필 필터링 검색 기능 구현
  server/src/main/java/com/mainproject/server/advice/ExceptionAdvice.java
  server/src/main/java/com/mainproject/server/constant/ErrorCode.java
  server/src/main/java/com/mainproject/server/image/dto/ImageResponseDto.java
  server/src/main/java/com/mainproject/server/image/service/ImageService.java
  server/src/main/java/com/mainproject/server/profile/dto/ProfileListResponseDto.java
  server/src/main/java/com/mainproject/server/profile/dto/ProfilePageDto.java
  server/src/main/java/com/mainproject/server/profile/dto/ProfileQueryDto.java
  server/src/main/java/com/mainproject/server/profile/dto/ProfileResponseDto.java
  server/src/main/java/com/mainproject/server/profile/entity/Profile.java
  server/src/main/java/com/mainproject/server/profile/repository/ProfileRepository.java
  server/src/main/java/com/mainproject/server/profile/repository/custom/CustomProfileRepository.java
  server/src/main/java/com/mainproject/server/profile/repository/custom/CustomProfileRepositoryImpl.java
  server/src/main/java/com/mainproject/server/profile/service/ProfileService.java
  server/src/main/java/com/mainproject/server/subject/dto/SubjectResponseDto.java
  server/src/main/java/com/mainproject/server/user/controller/UserController.java
  server/src/main/java/com/mainproject/server/user/dto/UserPatchDto.java
  server/src/main/java/com/mainproject/server/user/entity/User.java
  server/src/main/java/com/mainproject/server/user/repository/UserRepository.java
  server/src/main/java/com/mainproject/server/user/service/UserService.java
Labels: feat

#75 BE: Refactor Tutoring message
  server/src/main/java/com/mainproject/server/message/controller/MessageController.java
  server/src/main/java/com/mainproject/server/message/entity/Message.java
  server/src/main/java/com/mainproject/server/message/service/MessageService.java
  server/src/main/java/com/mainproject/server/profile/service/ProfileService.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringDto.java
  server/src/main/java/com/mainproject/server/tutoring/entity/Tutoring.java
  server/src/main/java/com/mainproject/server/tutoring/service/TutoringService.java
Labels: refactor

#78 Be/refactor: 서비스 로직 Todo 체크 제거 및 리팩토링
  server/src/main/java/com/mainproject/server/constant/ErrorCode.java
  server/src/main/java/com/mainproject/server/dateNotice/service/DateNoticeService.java
  server/src/main/java/com/mainproject/server/message/controller/MessageController.java
  server/src/main/java/com/mainproject/server/message/repository/MessageRoomRepository.java
  server/src/main/java/com/mainproject/server/message/service/MessageService.java
  server/src/main/java/com/mainproject/server/profile/repository/custom/CustomProfileRepository.java
  server/src/main/java/com/mainproject/server/profile/repository/custom/CustomProfileRepositoryImpl.java
  server/src/main/java/com/mainproject/server/profile/service/ProfileService.java
  server/src/main/java/com/mainproject/server/review/service/ReviewService.java
  server/src/main/java/com/mainproject/server/tutoring/controller/TutoringController.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringPatchDto.java
  server/src/main/java/com/mainproject/server/tutoring/service/TutoringService.java
Labels: refactor, fix

#76 Fe/feat tutoring page
  client/src/components/Modal.jsx
  client/src/components/Tutoring/DetailStar.jsx
  client/src/components/Tutoring/EditReviewModal.jsx
  client/src/components/Tutoring/FinishedJournalList.jsx
  client/src/components/Tutoring/FinishedJournalList.module.css
  client/src/components/Tutoring/JournalList.jsx
  client/src/components/Tutoring/JournalList.module.css
  client/src/components/Tutoring/ReviewDetail.jsx
  client/src/components/Tutoring/ReviewDetail.module.css
  client/src/components/Tutoring/ReviewModal.jsx
  client/src/components/Tutoring/ReviewModal.module.css
  client/src/components/Tutoring/StarRating.jsx
  client/src/components/Tutoring/StarRating.module.css
  client/src/components/Tutoring/dummyTutoringData.jsx
  client/src/pages/Tutoring.jsx
  client/src/pages/Tutoring.module.css
Labels: feat

#80 Fe/feat edit journal page
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/Button.module.css
  client/src/components/JournalSection/DatePicker.css
  client/src/components/JournalSection/DatePickerForm.jsx
  client/src/components/JournalSection/DatePickerForm.module.css
  client/src/components/JournalSection/DropDown.jsx
  client/src/components/JournalSection/DropDown.module.css
  client/src/components/JournalSection/EditJournalForm.jsx
  client/src/components/JournalSection/EditJournalForm.module.css
  client/src/components/JournalSection/JournalForm.jsx
  client/src/components/JournalSection/JournalForm.module.css
  client/src/components/JournalSection/TimePickerForm.jsx
  client/src/components/JournalSection/TimePickerForm.module.css
  client/src/components/profileSection/MyProfileCard.jsx
  client/src/components/profileSection/Toggle.jsx
  client/src/pages/EditJournal.jsx
  client/src/pages/EditJournal.module.css
  client/src/pages/Journal.jsx
  client/src/pages/Journal.module.css
  client/src/pages/MyProfile.jsx
  client/src/pages/MyProfile.module.css
  client/src/pages/TuteeProfile.jsx
  client/src/pages/TuteeProfile.module.css
  client/src/pages/TutorProfile.jsx
  client/src/pages/TutorProfile.module.css
Labels: feat

#77 feat: required 및 autosave 기능 구현 외
  client/src/assets/defaultUser.png
  client/src/components/Button.jsx
  client/src/components/Button.module.css
  client/src/components/ChangeProfile/ChangeProfileCard.jsx
  client/src/components/ChangeProfile/ChangeProfileCard.module.css
  client/src/components/ChangeProfile/ChangeProfileContents.jsx
  client/src/components/ChangeProfile/ChangeProfileContents.module.css
  client/src/components/ChangeProfile/SubjectsButtons.jsx
  client/src/components/ChangeProfile/TuteeContents.jsx
  client/src/components/ChangeProfile/TutorContents.jsx
  client/src/components/Header.jsx
  client/src/components/Header.module.css
  client/src/components/Input.jsx
  client/src/components/Input.module.css
  client/src/components/MainSection/FeedItem.jsx
  client/src/components/MainSection/FilterButton.jsx
  client/src/components/MainSection/SignUpForm.jsx
  client/src/components/MainSection/SignUpForm.module.css
  client/src/components/MainSection/UserInfoForm.jsx
  client/src/components/MainSection/UserInfoForm.module.css
  client/src/components/Message/MessageContent.module.css
  client/src/components/Modal.module.css
  client/src/components/profileSection/DummyData.jsx
  client/src/components/profileSection/MyProfileCard.jsx
  client/src/components/profileSection/MyProfileCard.module.css
  client/src/components/profileSection/ProfileCard.jsx
  client/src/components/profileSection/ProfileCard.module.css
  client/src/components/profileSection/ProfileContents.jsx
  client/src/components/profileSection/ProfileContents.module.css
  client/src/components/profileSection/Toggle.jsx
  client/src/components/profileSection/Toggle.module.css
  client/src/components/profileSection/TuteeContents.jsx
  client/src/components/profileSection/TutorContents.jsx
  client/src/pages/AddProfile.jsx
  client/src/pages/EditProfile.jsx
  client/src/pages/Message.module.css
  client/src/pages/MyProfile.jsx
  client/src/pages/MyProfile.module.css
  client/src/pages/TuteeList.jsx
  client/src/pages/TuteeProfile.jsx
  client/src/pages/TuteeProfile.module.css
  client/src/pages/TutorList.jsx
  client/src/pages/TutorProfile.jsx
  client/src/pages/TutorProfile.module.css
Labels: refactor, fix, feat

#83 Be/docs: Stub 튜터,튜티 회원 / 기본 프로필 이미지 / 각 회원별 프로필 / 프로필과 과목 관계 설정 Data Init
  server/src/main/java/com/mainproject/server/constant/ImageProperty.java
  server/src/main/java/com/mainproject/server/image/service/ImageService.java
  server/src/main/java/com/mainproject/server/profile/entity/Profile.java
  server/src/main/java/com/mainproject/server/profile/service/ProfileService.java
  server/src/main/resources/data.sql
Labels: todo

#91 Fe/fix edit journal page
  client/src/components/Input.module.css
  client/src/components/JournalSection/DatePicker.css
  client/src/components/JournalSection/DatePickerForm.jsx
  client/src/components/JournalSection/DatePickerForm.module.css
  client/src/components/JournalSection/DropDown.jsx
  client/src/components/JournalSection/DropDown.module.css
  client/src/components/JournalSection/EditJournalForm.jsx
  client/src/components/JournalSection/EditJournalForm.module.css
  client/src/components/JournalSection/JournalForm.jsx
  client/src/components/JournalSection/JournalForm.module.css
  client/src/components/JournalSection/TimePickerForm.jsx
  client/src/components/JournalSection/TimePickerForm.module.css
  client/src/components/JournalSection/react-datepicker.css
  client/src/components/modal/DefaultModal.jsx
  client/src/components/modal/GlobalModal.jsx
  client/src/components/profileSection/DummyData.jsx
  client/src/components/profileSection/MyProfileCard.jsx
  client/src/components/profileSection/ProfileCard.jsx
  client/src/components/profileSection/Toggle.jsx
  client/src/pages/EditJournal.jsx
  client/src/pages/EditProfile.jsx
  client/src/pages/Journal.jsx
  client/src/pages/MyProfile.jsx
  client/src/pages/TutorProfile.jsx
Labels: fix

#85 BE/refactor: Service 로직 리팩토링 및 예외 처리
  server/src/main/java/com/mainproject/server/constant/ErrorCode.java
  server/src/main/java/com/mainproject/server/constant/HomeworkStatus.java
  server/src/main/java/com/mainproject/server/constant/TutoringStatus.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/DateNoticePatchDto.java
  server/src/main/java/com/mainproject/server/dateNotice/entity/DateNotice.java
  server/src/main/java/com/mainproject/server/dateNotice/entity/Homework.java
  server/src/main/java/com/mainproject/server/dateNotice/service/DateNoticeService.java
  server/src/main/java/com/mainproject/server/message/entity/MessageRoom.java
  server/src/main/java/com/mainproject/server/message/service/MessageService.java
  server/src/main/java/com/mainproject/server/profile/dto/ProfilePageDto.java
  server/src/main/java/com/mainproject/server/profile/dto/ProfileQueryDto.java
  server/src/main/java/com/mainproject/server/profile/entity/Profile.java
  server/src/main/java/com/mainproject/server/profile/repository/custom/CustomProfileRepository.java
  server/src/main/java/com/mainproject/server/profile/repository/custom/CustomProfileRepositoryImpl.java
  server/src/main/java/com/mainproject/server/profile/service/ProfileService.java
  server/src/main/java/com/mainproject/server/review/controller/ReviewController.java
  server/src/main/java/com/mainproject/server/review/dto/ReviewPatchDto.java
  server/src/main/java/com/mainproject/server/review/entity/Review.java
  server/src/main/java/com/mainproject/server/review/mapper/ReviewMapper.java
  server/src/main/java/com/mainproject/server/review/repository/ReviewRepository.java
  server/src/main/java/com/mainproject/server/review/service/ReviewService.java
  server/src/main/java/com/mainproject/server/tutoring/controller/TutoringController.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringDto.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringPatchDto.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringResponseDto.java
  server/src/main/java/com/mainproject/server/tutoring/repository/TutoringRepository.java
  server/src/main/java/com/mainproject/server/tutoring/service/TutoringService.java
  server/src/main/resources/data.sql
Labels: refactor

#86 Fe/refactor modal mk
  client/src/components/Tutoring/EditReviewModal.jsx
  client/src/components/Tutoring/FinishedJournalList.jsx
  client/src/components/Tutoring/JournalList.jsx
  client/src/components/Tutoring/ReviewDetail.jsx
  client/src/components/Tutoring/ReviewModal.jsx
  client/src/components/modal/EditReviewModal.jsx
  client/src/components/modal/GlobalModal.jsx
  client/src/components/modal/ReviewDetail.jsx
  client/src/components/modal/ReviewDetail.module.css
  client/src/components/modal/ReviewModal.jsx
  client/src/components/modal/ReviewModal.module.css
  client/src/components/profileSection/ProfileCard.jsx
  client/src/components/profileSection/Toggle.jsx
  client/src/pages/TuteeProfile.jsx
  client/src/util/DetailStar.jsx
  client/src/util/StarRating.jsx
  client/src/util/StarRating.module.css
Labels: refactor

#87 refactor: 전역 모달 관리 리팩토링
  client/src/App.jsx
  client/src/components/AdminModal.jsx
  client/src/components/ChangeProfile/ChangeProfileCard.jsx
  client/src/components/Header.jsx
  client/src/components/Header.module.css
  client/src/components/Message/MessageContent.jsx
  client/src/components/modal/AdminModal.jsx
  client/src/components/modal/AdminModal.module.css
  client/src/components/modal/BothHandlerModal.jsx
  client/src/components/modal/GlobalModal.jsx
  client/src/pages/AddProfile.jsx
  client/src/pages/EditProfile.jsx
Labels: refactor

#93 Be/refactor : Security 적용 및 리팩토링
  server/src/main/java/com/mainproject/server/auth/token/JwtTokenizer.java
  server/src/main/java/com/mainproject/server/config/SecurityConfig.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/DateNoticePatchDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/HomeworkPatchDto.java
  server/src/main/java/com/mainproject/server/dateNotice/entity/DateNotice.java
  server/src/main/java/com/mainproject/server/dateNotice/entity/Homework.java
  server/src/main/java/com/mainproject/server/dateNotice/repository/HomeworkRepository.java
  server/src/main/java/com/mainproject/server/dateNotice/service/DateNoticeService.java
  server/src/main/java/com/mainproject/server/image/service/ImageService.java
  server/src/main/java/com/mainproject/server/message/entity/Message.java
  server/src/main/java/com/mainproject/server/message/entity/MessageRoom.java
  server/src/main/java/com/mainproject/server/message/service/MessageService.java
  server/src/main/java/com/mainproject/server/profile/entity/Profile.java
  server/src/main/java/com/mainproject/server/profile/repository/custom/CustomProfileRepositoryImpl.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringDto.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringResponseDto.java
  server/src/main/java/com/mainproject/server/tutoring/entity/Tutoring.java
  server/src/main/java/com/mainproject/server/user/controller/UserController.java
  server/src/main/java/com/mainproject/server/user/service/UserService.java
  server/src/main/resources/application.yml
  server/src/main/resources/data.sql
Labels: refactor

#95 Fe/feat routing
  client/src/components/Header.jsx
  client/src/components/Header.module.css
  client/src/components/JournalSection/DropDown.jsx
  client/src/components/JournalSection/EditJournalForm.jsx
  client/src/components/JournalSection/JournalForm.jsx
  client/src/components/MainSection/FeedItem.jsx
  client/src/components/MainSection/FilterButton.jsx
  client/src/components/MainSection/FilterDropdown.jsx
  client/src/components/MainSection/FilterDropdown.module.css
  client/src/components/MainSection/LoginForm.jsx
  client/src/components/MainSection/SignUpForm.jsx
  client/src/components/Message/MessageContent.jsx
  client/src/components/Message/MessageList.jsx
  client/src/components/Message/MessageList.module.css
  client/src/components/Tutoring/FinishedJournalList.jsx
  client/src/components/Tutoring/JournalList.jsx
  client/src/components/modal/AdminModal.jsx
  client/src/components/modal/ReviewDetail.jsx
  client/src/components/profileSection/MyProfileCard.jsx
  client/src/components/profileSection/ProfileCard.jsx
  client/src/pages/Admin.jsx
  client/src/pages/Admin.module.css
  client/src/pages/TuteeList.jsx
  client/src/pages/TuteeList.module.css
  client/src/pages/TutorList.jsx
  client/src/pages/TutoringList.jsx
Labels: feat

#96 refactor: SecurityConfig 권한 설정 오타 수정
  server/src/main/java/com/mainproject/server/auth/redis/entity/RefreshEntity.java
  server/src/main/java/com/mainproject/server/auth/token/JwtTokenizer.java
  server/src/main/java/com/mainproject/server/config/SecurityConfig.java
Labels: refactor

#98 feat:date time picker 및 자동 저장 기능 구현, 페이지 연결 등
  client/.stylelintrc.json
  client/src/App.jsx
  client/src/components/JournalSection/DatePicker.css
  client/src/components/JournalSection/DatePickerForm.jsx
  client/src/components/JournalSection/DatePickerForm.module.css
  client/src/components/JournalSection/DropDown.jsx
  client/src/components/JournalSection/DropDown.module.css
  client/src/components/JournalSection/EditJournalForm.jsx
  client/src/components/JournalSection/EditJournalForm.module.css
  client/src/components/JournalSection/JournalForm.jsx
  client/src/components/Tutoring/JournalList.jsx
  client/src/pages/AddJournal.jsx
  client/src/pages/ChangeJournal.module.css
  client/src/pages/EditJournal.jsx
  client/src/pages/Journal.jsx
Labels: fix, feat

#99 chore: 오타 수정 및 샘플 UserServiceTest 작성
  server/src/main/java/com/mainproject/server/config/SecurityConfig.java
  server/src/main/java/com/mainproject/server/user/service/UserService.java
  server/src/main/resources/application.yml
  server/src/test/java/com/mainproject/server/user/service/UserServiceTest.java
Labels: todo

#107 Be/fix oauth2 provider user login
  .github/ISSUE_TEMPLATE/template.md
  .github/workflows/gradle.yml
  .gitignore
  server/appspec.yml
  server/build.gradle
  server/scripts/deploy.sh
  server/src/main/java/com/mainproject/server/auth/oauth2/provider/CustomOAuth2Provider.java
  server/src/main/java/com/mainproject/server/home/HomeController.java
  server/src/main/java/com/mainproject/server/image/controller/ImageController.java
  server/src/main/java/com/mainproject/server/profile/service/ProfileService.java
  server/src/main/java/com/mainproject/server/tutoring/controller/TutoringController.java
  server/src/main/java/com/mainproject/server/user/service/UserService.java
  server/src/test/java/com/mainproject/server/home/HomeControllerTest.java
Labels: fix

#114 BE: refactor 유효성 검증 추가 및 누락 필드 수정
  server/src/main/java/com/mainproject/server/auth/redis/entity/RefreshEntity.java
  server/src/main/java/com/mainproject/server/auth/token/JwtTokenizer.java
  server/src/main/java/com/mainproject/server/config/SecurityConfig.java
  server/src/main/java/com/mainproject/server/constant/ErrorCode.java
  server/src/main/java/com/mainproject/server/profile/dto/ProfilePageDto.java
  server/src/main/java/com/mainproject/server/profile/dto/ProfileResponseDto.java
  server/src/main/java/com/mainproject/server/profile/repository/custom/CustomProfileRepository.java
  server/src/main/java/com/mainproject/server/profile/repository/custom/CustomProfileRepositoryImpl.java
  server/src/main/java/com/mainproject/server/profile/service/ProfileService.java
  server/src/main/java/com/mainproject/server/user/dto/UserPatchDto.java
  server/src/main/java/com/mainproject/server/user/service/UserService.java
Labels: refactor

#118 Be/test: 회원 테스트 코드 작성 및 리팩토링
  server/src/main/java/com/mainproject/server/config/SecurityConfig.java
  server/src/main/java/com/mainproject/server/constant/ErrorCode.java
  server/src/main/java/com/mainproject/server/tutoring/controller/TutoringController.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringPostDto.java
  server/src/main/java/com/mainproject/server/user/controller/UserController.java
  server/src/main/java/com/mainproject/server/user/service/UserService.java
  server/src/test/java/com/mainproject/server/user/service/UserServiceTest.java
Labels: refactor, test

#120 Be/test: 프로필 서비스 로직 테스트 코드 작성 및 리팩토링
  server/src/main/java/com/mainproject/server/audit/Auditable.java
  server/src/main/java/com/mainproject/server/profile/controller/ProfileController.java
  server/src/main/java/com/mainproject/server/profile/service/ProfileService.java
  server/src/main/java/com/mainproject/server/user/controller/UserController.java
  server/src/main/java/com/mainproject/server/utils/ResponseStubData.java
  server/src/test/java/com/mainproject/server/profile/service/ProfileServiceTest.java
Labels: test

#121 Be/tutoring service test
  server/src/main/java/com/mainproject/server/tutoring/service/TutoringService.java
  server/src/test/java/com/mainproject/server/tutoring/service/TutoringServiceTest.java
Labels: refactor, test

#127 fix: Page Response Page Number 수정
  server/src/main/java/com/mainproject/server/dto/PageResponseDto.java
Labels: fix

#131 Be/refactor: 회원 첫 정보 수정 시 기본 프로필 생성 기능 추가
  server/src/main/java/com/mainproject/server/config/SecurityConfig.java
  server/src/main/java/com/mainproject/server/constant/ErrorCode.java
  server/src/main/java/com/mainproject/server/constant/WantedStatus.java
  server/src/main/java/com/mainproject/server/image/service/ImageService.java
  server/src/main/java/com/mainproject/server/profile/entity/Profile.java
  server/src/main/java/com/mainproject/server/profile/service/ProfileService.java
  server/src/main/java/com/mainproject/server/user/service/UserService.java
  server/src/test/java/com/mainproject/server/profile/service/ProfileServiceTest.java
  server/src/test/java/com/mainproject/server/user/service/UserServiceTest.java
Labels: refactor, feat

#133 Be/test 과외 일지 서비스 테스트 코드 작성
  server/src/main/java/com/mainproject/server/dateNotice/service/DateNoticeService.java
  server/src/main/java/com/mainproject/server/utils/ResponseStubData.java
  server/src/main/java/com/mainproject/server/utils/StubData.java
  server/src/test/java/com/mainproject/server/dateNotice/service/DateNoticeServiceTest.java
  server/src/test/java/com/mainproject/server/profile/service/ProfileServiceTest.java
  server/src/test/java/com/mainproject/server/tutoring/service/TutoringServiceTest.java
Labels: test

#135 Be/test : 후기 서비스 로직 테스트 코드 작성
  server/src/main/java/com/mainproject/server/review/service/ReviewService.java
  server/src/main/java/com/mainproject/server/utils/StubData.java
  server/src/test/java/com/mainproject/server/review/service/ReviewServiceTest.java
Labels: test

#138 Be/test: JwtTokenizer 테스트 코드 작성
  server/src/main/java/com/mainproject/server/auth/redis/dto/RefreshDto.java
  server/src/main/java/com/mainproject/server/auth/token/JwtTokenizer.java
  server/src/main/java/com/mainproject/server/subject/service/SubjectService.java
  server/src/test/java/com/mainproject/server/auth/token/JwtTokenizerTest.java
Labels: test

#141 Be/test: Auth Controller 테스트 코드 작성
  .github/workflows/gradle.yml
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/mainproject/server/auth/controller/AuthController.java
  server/src/main/java/com/mainproject/server/utils/StubData.java
  server/src/test/java/com/mainproject/server/auth/controller/AuthControllerTest.java
Labels: test

#136 feat: 메인 섹션 API 연결
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/Footer.jsx
  client/src/components/Footer.module.css
  client/src/components/Header.jsx
  client/src/components/Header.module.css
  client/src/components/JournalSection/DatePickerForm.jsx
  client/src/components/JournalSection/EditJournalForm.jsx
  client/src/components/LoadingIndicator.jsx
  client/src/components/LoadingIndicator.module.css
  client/src/components/MainSection/FeedItem.jsx
  client/src/components/MainSection/FeedItem.module.css
  client/src/components/MainSection/LoginForm.jsx
  client/src/components/MainSection/LoginForm.module.css
  client/src/components/MainSection/UserInfoForm.jsx
  client/src/components/MainSection/UserInfoForm.module.css
  client/src/components/modal/AdminModal.jsx
  client/src/components/modal/AdminModal.module.css
  client/src/components/modal/DefaultModal.jsx
  client/src/components/modal/GlobalModal.jsx
  client/src/components/modal/HandlerAlertModal.jsx
  client/src/pages/AddJournal.jsx
  client/src/pages/Admin.jsx
  client/src/pages/Admin.module.css
  client/src/pages/TuteeList.jsx
  client/src/pages/TuteeList.module.css
  client/src/pages/TutorList.jsx
  client/src/pages/TutorList.module.css
  client/src/recoil/journal.js
  client/src/recoil/profile.js
  client/src/util/reIssueToken.js
  client/src/util/useDidMountEffect.js
  client/src/util/useScroll.js
  client/src/util/validation.js
Labels: refactor, fix, feat

#140 Fe/feat profile section api
  client/src/App.jsx
  client/src/components/ChangeProfile/ChangeProfileCard.jsx
  client/src/components/ChangeProfile/ChangeProfileCard.module.css
  client/src/components/MainSection/SignUpForm.jsx
  client/src/components/MainSection/SignUpForm.module.css
  client/src/components/modal/GlobalModal.jsx
  client/src/components/modal/HandlerAlertModal.jsx
  client/src/components/modal/ImgLoadModal.jsx
  client/src/components/modal/ImgLoadModal.module.css
  client/src/components/profileSection/MyProfileCard.jsx
  client/src/components/profileSection/ProfileCard.jsx
  client/src/components/profileSection/ProfileContents.jsx
  client/src/components/profileSection/Toggle.jsx
  client/src/components/profileSection/TutorContents.jsx
  client/src/pages/EditProfile.jsx
  client/src/pages/MyProfile.jsx
  client/src/pages/TestPage.jsx
  client/src/pages/TuteeProfile.jsx
  client/src/pages/TutorProfile.jsx
  client/src/pages/TutoringList.jsx
  client/src/pages/TutoringList.module.css
  client/src/util/Pagination.jsx
  client/src/util/Pagination.module.css
Labels: refactor, fix, feat

#144 fix: User Patch Phone Number 벨리데이션 수정 11자리 숫자
  server/src/main/java/com/mainproject/server/user/dto/UserPatchDto.java
Labels: fix

#146 Be/test: 회원 컨트롤러 테스트 작성
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/mainproject/server/auth/controller/AuthController.java
  server/src/main/java/com/mainproject/server/auth/dto/PasswordDto.java
  server/src/main/java/com/mainproject/server/dto/ErrorResponse.java
  server/src/main/java/com/mainproject/server/user/controller/UserController.java
  server/src/main/java/com/mainproject/server/user/dto/UserPatchDto.java
  server/src/main/java/com/mainproject/server/user/dto/UserPostDto.java
  server/src/main/java/com/mainproject/server/user/service/UserService.java
  server/src/main/java/com/mainproject/server/utils/ResponseStubData.java
  server/src/main/java/com/mainproject/server/utils/StubData.java
  server/src/test/java/com/mainproject/server/user/controller/UserControllerTest.java
  server/src/test/java/com/mainproject/server/user/service/UserServiceTest.java
Labels: test

#147 Be/test: 회원 컨트롤러 테스트 코드 작성 및 리팩토링
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/mainproject/server/auth/dto/PasswordDto.java
  server/src/main/java/com/mainproject/server/utils/ResponseStubData.java
  server/src/main/resources/static/docs/index.html
  server/src/test/java/com/mainproject/server/user/controller/UserControllerTest.java
Labels: test

#149 Be/fix: Security 수정 / CORS ISSUE
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/mainproject/server/config/SecurityConfig.java
Labels: fix

#151 Fe/feat add profile api
  client/src/App.jsx
  client/src/components/ChangeProfile/ChangeProfileCard.jsx
  client/src/components/ChangeProfile/ChangeProfileCard.module.css
  client/src/components/Header.jsx
  client/src/components/Header.module.css
  client/src/components/MainSection/UserInfoForm.jsx
  client/src/components/modal/AdminModal.jsx
  client/src/components/modal/ImgLoadModal.jsx
  client/src/components/profileSection/MyProfileCard.jsx
  client/src/components/profileSection/MyProfileCard.module.css
  client/src/components/profileSection/ProfileCard.jsx
  client/src/components/profileSection/ProfileCard.module.css
  client/src/pages/Admin.jsx
  client/src/pages/Admin.module.css
  client/src/pages/EditProfile.jsx
  client/src/util/reIssueToken.js
Labels: refactor, feat

#159 Be/feat: Tutoring PATCH API & test: Profile Controller TEST
  server/.gitignore
  server/src/main/java/com/mainproject/server/constant/ErrorCode.java
  server/src/main/java/com/mainproject/server/constant/TutoringStatus.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/DateNoticePostDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/HomeworkPostDto.java
  server/src/main/java/com/mainproject/server/dateNotice/mapper/DateNoticeMapper.java
  server/src/main/java/com/mainproject/server/profile/controller/ProfileController.java
  server/src/main/java/com/mainproject/server/profile/dto/ProfileDto.java
  server/src/main/java/com/mainproject/server/review/service/ReviewService.java
  server/src/main/java/com/mainproject/server/tutoring/controller/TutoringController.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringPatchDto.java
  server/src/main/java/com/mainproject/server/tutoring/repository/TutoringRepository.java
  server/src/main/java/com/mainproject/server/tutoring/service/TutoringService.java
  server/src/main/java/com/mainproject/server/utils/StubData.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application.yml
  server/src/main/resources/static/docs/index.html
  server/src/test/java/com/mainproject/server/profile/controller/ProfileControllerTest.java
  server/src/test/java/com/mainproject/server/tutoring/service/TutoringServiceTest.java
Labels: feat, test

#162 Be/test: 프로필 컨트롤러 테스트 코드 작성 및 리팩토링
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/mainproject/server/advice/ExceptionAdvice.java
  server/src/main/java/com/mainproject/server/constant/ErrorCode.java
  server/src/test/java/com/mainproject/server/profile/controller/ProfileControllerTest.java
  server/src/test/java/com/mainproject/server/user/controller/UserControllerTest.java
Labels: refactor, test

#164 Be/refactor: Tutoring & Review 응답 필드 추가
  server/src/main/java/com/mainproject/server/review/controller/ReviewController.java
  server/src/main/java/com/mainproject/server/review/service/ReviewService.java
  server/src/main/java/com/mainproject/server/tutoring/controller/TutoringController.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringDto.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringPatchDto.java
  server/src/main/java/com/mainproject/server/tutoring/dto/TutoringResponseDto.java
  server/src/main/java/com/mainproject/server/tutoring/mapper/TutoringMapper.java
  server/src/main/java/com/mainproject/server/utils/ResponseStubData.java
Labels: refactor

#166 Be/refactor Tutoring & MessageRoom
  server/src/main/java/com/mainproject/server/message/dto/MessageRoomResponseDto.java
  server/src/main/java/com/mainproject/server/tutoring/service/TutoringService.java
Labels: refactor

#167 chore: getTutoring 오류 수정
  server/src/main/java/com/mainproject/server/tutoring/service/TutoringService.java
Labels: fix

#168 Be/review service fix
  server/src/main/java/com/mainproject/server/review/service/ReviewService.java
  server/src/main/java/com/mainproject/server/tutoring/service/TutoringService.java
Labels: refactor, fix

#169 chore: updateReview setRate 수정
  server/src/main/java/com/mainproject/server/review/service/ReviewService.java
Labels: fix

#170 chore: Rate 계산 방식 변경
  server/src/main/java/com/mainproject/server/review/service/ReviewService.java
Labels: fix

#171 Fe/feat tutoring api
  client/src/App.jsx
  client/src/components/LoadingIndicator.jsx
  client/src/components/LoadingIndicator.module.css
  client/src/components/Tutoring/FinishedJournalList.jsx
  client/src/components/Tutoring/FinishedJournalList.module.css
  client/src/components/Tutoring/JournalList.jsx
  client/src/components/Tutoring/JournalList.module.css
  client/src/components/Tutoring/Journals.jsx
  client/src/components/Tutoring/dummyTutoringData.jsx
  client/src/components/modal/EditReviewModal.jsx
  client/src/components/modal/ReviewDetail.jsx
  client/src/components/modal/ReviewModal.jsx
  client/src/pages/Tutoring.jsx
  client/src/util/StarRating.jsx
  client/src/util/useScroll.js
Labels: feat

#172 feat: 과외 일지 관련 API 연결 외
  client/src/App.jsx
  client/src/components/ChangeProfile/ChangeProfileCard.jsx
  client/src/components/Footer.jsx
  client/src/components/Header.jsx
  client/src/components/JournalSection/DatePickerForm.jsx
  client/src/components/JournalSection/DropDown.jsx
  client/src/components/JournalSection/EditJournalForm.jsx
  client/src/components/JournalSection/EditJournalForm.module.css
  client/src/components/JournalSection/JournalForm.jsx
  client/src/components/MainSection/LoginForm.jsx
  client/src/components/MainSection/UserInfoForm.jsx
  client/src/components/modal/AdminModal.jsx
  client/src/components/profileSection/MyProfileCard.jsx
  client/src/components/profileSection/ProfileCard.jsx
  client/src/pages/AddJournal.jsx
  client/src/pages/Admin.jsx
  client/src/pages/EditJournal.jsx
  client/src/pages/EditProfile.jsx
  client/src/pages/Journal.jsx
  client/src/pages/TuteeList.jsx
  client/src/pages/TuteeList.module.css
  client/src/pages/TutorList.jsx
  client/src/pages/TutorList.module.css
  client/src/recoil/journal.js
  client/src/util/useScroll.js
Labels: fix, feat

#174 Fe/feat profil list api
  client/src/components/Header.jsx
  client/src/components/MainSection/LoginForm.jsx
  client/src/components/MainSection/LoginForm.module.css
  client/src/components/MainSection/UserInfoForm.jsx
  client/src/components/MainSection/UserInfoForm.module.css
  client/src/components/Message/Chat.jsx
  client/src/components/Message/MessageContent.jsx
  client/src/components/Message/MessageList.jsx
  client/src/components/TutoringList/Tutoring.jsx
  client/src/components/TutoringList/Tutoring.module.css
  client/src/components/modal/DefaultModal.jsx
  client/src/components/modal/GlobalModal.jsx
  client/src/components/modal/RedModals.jsx
  client/src/pages/Message.jsx
  client/src/pages/TutoringList.jsx
  client/src/pages/TutoringList.module.css
  client/src/recoil/currentRoomId.js
  client/src/recoil/tutoringTitle.js
Labels: fix, feat

#173 be/test: TutoringController Test 코드 작성 및 Rest Docs 작성
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/mainproject/server/dateNotice/dto/DateNoticeSimpleResponseDto.java
  server/src/main/java/com/mainproject/server/dateNotice/dto/HomeworkResponseDto.java
  server/src/main/java/com/mainproject/server/message/dto/MessageRoomSimpleResponseDto.java
  server/src/test/java/com/mainproject/server/tutoring/controller/TutoringControllerTest.java
Labels: test

#176 refactor: Message Room Response SenderId 필드 추가
  server/src/main/java/com/mainproject/server/message/dto/MessageRoomSimpleResponseDto.java
Labels: refactor

#179 refactor: column name 중복 수정
  server/src/main/java/com/mainproject/server/dateNotice/entity/DateNotice.java
  server/src/main/java/com/mainproject/server/dateNotice/entity/Homework.java
  server/src/main/java/com/mainproject/server/message/entity/Message.java
  server/src/main/java/com/mainproject/server/message/entity/MessageRoom.java
  server/src/main/java/com/mainproject/server/profile/entity/Profile.java
  server/src/main/java/com/mainproject/server/review/entity/Review.java
  server/src/main/java/com/mainproject/server/subject/entity/SubjectProfile.java
  server/src/main/java/com/mainproject/server/tutoring/entity/Tutoring.java
  server/src/main/java/com/mainproject/server/user/entity/User.java
  server/src/main/resources/data.sql
Labels: fix

#180 fix: user roles 관련 수정
  server/src/main/java/com/mainproject/server/user/entity/User.java
  server/src/main/resources/data.sql
Labels: fix

#183 Fe/fix mk
  client/src/App.jsx
  client/src/components/ChangeProfile/ChangeProfileContents.jsx
  client/src/components/JournalSection/DropDown.jsx
  client/src/components/JournalSection/EditJournalForm.jsx
  client/src/components/JournalSection/JournalForm.jsx
  client/src/components/Message/MessageContent.jsx
  client/src/components/Tutoring/FinishedJournalList.jsx
  client/src/components/Tutoring/JournalList.jsx
  client/src/components/Tutoring/Journals.jsx
  client/src/components/modal/DefaultModal.jsx
  client/src/components/profileSection/MyProfileCard.jsx
  client/src/components/profileSection/ProfileCard.jsx
  client/src/components/profileSection/ProfileContents.module.css
  client/src/components/profileSection/TuteeContents.jsx
  client/src/components/profileSection/TutorContents.jsx
  client/src/pages/Admin.jsx
  client/src/pages/EditJournal.jsx
  client/src/pages/Journal.jsx
  client/src/pages/TuteeList.jsx
  client/src/pages/TuteeProfile.jsx
  client/src/pages/TutorList.jsx
  client/src/pages/TutorProfile.jsx
  client/src/pages/Tutoring.jsx
Labels: fix

#184 Fe/fix duru
  client/src/components/Header.module.css
  client/src/components/Message/Chat.jsx
  client/src/components/Message/Chat.module.css
  client/src/components/Message/MessageContent.jsx
  client/src/components/Message/MessageList.jsx
  client/src/components/Message/MessageList.module.css
  client/src/components/TutoringList/Tutoring.jsx
  client/src/pages/Message.jsx
  client/src/pages/TutoringList.jsx
  client/src/pages/TutoringList.module.css
Labels: fix

#185 fix: 각종 issue 해결 #178
  client/src/components/ChangeProfile/ChangeProfileCard.jsx
  client/src/components/MainSection/LoginForm.jsx
  client/src/components/Tutoring/FinishedJournalList.jsx
  client/src/components/Tutoring/FinishedJournalList.module.css
  client/src/components/Tutoring/JournalList.jsx
  client/src/components/Tutoring/JournalList.module.css
  client/src/components/Tutoring/Journals.jsx
  client/src/components/modal/AdminModal.module.css
  client/src/components/modal/ReviewModal.module.css
  client/src/pages/Tutoring.jsx
Labels: fix, feat

#188 Be/test: Review Controller & refactor: Message Room Service
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/mainproject/server/constant/ErrorCode.java
  server/src/main/java/com/mainproject/server/message/repository/MessageRoomRepository.java
  server/src/main/java/com/mainproject/server/message/service/MessageService.java
  server/src/main/java/com/mainproject/server/review/dto/ReviewPatchDto.java
  server/src/main/java/com/mainproject/server/review/dto/ReviewPostDto.java
  server/src/main/java/com/mainproject/server/tutoring/service/TutoringService.java
  server/src/test/java/com/mainproject/server/review/controller/ReviewControllerTest.java
  server/src/test/java/com/mainproject/server/tutoring/service/TutoringServiceTest.java
Labels: refactor, test

#189 refactor: CORS Custom Filter 배포 테스트
  server/src/main/java/com/mainproject/server/auth/filter/CorsFilter.java
  server/src/main/java/com/mainproject/server/config/RedisConfig.java
  server/src/main/java/com/mainproject/server/config/SecurityConfig.java
Labels: test

#190 refactor: CORS Custom Filter Origin Set Header 수정
  server/src/main/java/com/mainproject/server/auth/filter/CorsFilter.java
Labels: test

#191 refactor: CORS Custom Filter Origin Set Header 수정
  server/src/main/java/com/mainproject/server/auth/filter/CorsFilter.java
Labels: test

#192 refactor: CORS Custom Filter Origin Set Header 재수정
  server/src/main/java/com/mainproject/server/auth/filter/CorsFilter.java
Labels: fix, feat

#193 refactor: CORS Custom Filter Origin Set Header 재 수정
  server/src/main/java/com/mainproject/server/auth/filter/CorsFilter.java
Labels: refactor, fix

#194 refactor: CORS Custom Filter Origin 응답 헤더 수정
  server/src/main/java/com/mainproject/server/auth/filter/CorsFilter.java
Labels: refactor, fix

#196 refactor: CORS Custom Filter & OAuth2 Redirect Url 수정
  server/src/main/java/com/mainproject/server/auth/filter/CorsFilter.java
  server/src/main/java/com/mainproject/server/auth/oauth2/provider/CustomOAuth2Provider.java
Labels: fix

#200 be/refactor: OAuth2 로그인 후 인증 되지 않는 문제 확인하기 위하여 Log 추가
  server/src/main/java/com/mainproject/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/mainproject/server/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/mainproject/server/auth/oauth2/OAuth2UserSuccessHandler.java
Labels: fix

#202 chore: 불필요한 주석 제거 & Debug 위한 로그 작성
  server/src/main/java/com/mainproject/server/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/mainproject/server/auth/oauth2/OAuth2UserSuccessHandler.java
Labels: refactor

#203 chore: OAuth2 로그인 후 토큰 발급시 Bearer 누락
  server/src/main/java/com/mainproject/server/auth/oauth2/OAuth2UserSuccessHandler.java
Labels: fix

#204 chore: OAuth2 추가 메소드 부분 불필요하여 RollBack
  server/src/main/java/com/mainproject/server/auth/oauth2/OAuth2UserSuccessHandler.java
Labels: fix

#205 Be/refactor: Message Service
  server/src/main/java/com/mainproject/server/auth/filter/CorsFilter.java
  server/src/main/java/com/mainproject/server/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/mainproject/server/auth/oauth2/OAuth2UserSuccessHandler.java
  server/src/main/java/com/mainproject/server/constant/ErrorCode.java
  server/src/main/java/com/mainproject/server/message/service/MessageService.java
Labels: refactor

#207 feat:MessageService Test
  server/src/test/java/com/mainproject/server/message/MessageServiceTest.java
Labels: test

#208 test: Message Service Test Code Refactor
  server/src/main/java/com/mainproject/server/message/entity/Message.java
  server/src/main/java/com/mainproject/server/message/service/MessageService.java
  server/src/test/java/com/mainproject/server/message/MessageServiceTest.java
Labels: test

#209 Fe/fix after distribution
  client/src/components/Message/Chat.jsx
  client/src/components/Message/MessageContent.jsx
  client/src/components/Message/MessageContent.module.css
  client/src/components/profileSection/ProfileCard.jsx
  client/src/pages/Message.jsx
Labels: fix, feat

#210 Fe/fix inquire button mk
  client/src/App.jsx
  client/src/components/ChangeProfile/ChangeProfileCard.jsx
  client/src/components/ChangeProfile/ChangeProfileContents.jsx
  client/src/components/Header.jsx
  client/src/components/JournalSection/DropDown.jsx
  client/src/components/JournalSection/EditJournalForm.jsx
  client/src/components/JournalSection/JournalForm.jsx
  client/src/components/MainSection/LoginForm.jsx
  client/src/components/MainSection/UserInfoForm.jsx
  client/src/components/Message/MessageList.jsx
  client/src/components/Tutoring/FinishedJournalList.jsx
  client/src/components/Tutoring/JournalList.jsx
  client/src/components/Tutoring/Journals.jsx
  client/src/components/TutoringList/Tutoring.jsx
  client/src/components/modal/ImgLoadModal.jsx
  client/src/components/profileSection/DummyData.jsx
  client/src/components/profileSection/MyProfileCard.jsx
  client/src/components/profileSection/ProfileCard.jsx
  client/src/components/profileSection/Toggle.jsx
  client/src/components/profileSection/TutorContents.jsx
  client/src/pages/AddProfile.jsx
  client/src/pages/Admin.jsx
  client/src/pages/TuteeList.jsx
  client/src/pages/TuteeProfile.jsx
  client/src/pages/TutorList.jsx
Labels: fix

#211 fix: 배포 후 이슈 사항 해결 #206
  client/src/components/Header.jsx
  client/src/components/Header.module.css
  client/src/components/MainSection/FilterDropdown.jsx
  client/src/components/Message/MessageContent.jsx
  client/src/index.jsx
  client/src/pages/TutorList.jsx
  client/src/util/useOutSideRef.js
Labels: fix

#213 Be/refactor: Message Room 유효성 검증 추가
  server/src/main/java/com/mainproject/server/constant/ErrorCode.java
  server/src/main/java/com/mainproject/server/message/service/MessageService.java
  server/src/main/java/com/mainproject/server/user/entity/User.java
  server/src/main/java/com/mainproject/server/user/service/UserService.java
Labels: refactor

#214 Be/test: 메세지 컨트롤러 테스트 코드 작성 및 REST Docs 반영
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/mainproject/server/message/controller/MessageController.java
  server/src/main/java/com/mainproject/server/utils/ResponseStubData.java
  server/src/test/java/com/mainproject/server/message/controller/MessageControllerTest.java
Labels: refactor, test

#216 Be/test: 이미지 업로드 컨트롤러 테스트 코드 작성 및 REST Docs 반영
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/mainproject/server/image/controller/ImageController.java
  server/src/main/resources/static/image/test.jpg
  server/src/test/java/com/mainproject/server/image/controller/ImageControllerTest.java
  server/src/test/java/com/mainproject/server/message/controller/MessageControllerTest.java
Labels: test

#220 refactor: Tutoring 종료 시 Message Room의 tutoringId 삭제 하도록 수정
  server/src/main/java/com/mainproject/server/message/service/MessageService.java
  server/src/main/java/com/mainproject/server/tutoring/service/TutoringService.java
Labels: refactor

#221 refactor: Tutoring 종료 시 Message Room의 tutoringId 삭제 하도록 수정
  server/src/main/java/com/mainproject/server/review/service/ReviewService.java
  server/src/main/java/com/mainproject/server/tutoring/service/TutoringService.java
Labels: fix

#224 Be/refactor: 회원 탈퇴시 비활성화 상태로 수정
  server/src/main/java/com/mainproject/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/mainproject/server/auth/oauth2/OAuth2UserSuccessHandler.java
  server/src/main/java/com/mainproject/server/constant/ErrorCode.java
  server/src/main/java/com/mainproject/server/constant/UserStatus.java
  server/src/main/java/com/mainproject/server/user/service/UserService.java
Labels: refactor

#225 refactor: 일반 및 소셜 로그인 시 비활성 회원 예외 처리
  server/src/main/java/com/mainproject/server/auth/details/UserCustomDetailsService.java
  server/src/main/java/com/mainproject/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/mainproject/server/auth/handler/UserAuthenticationFailureHandler.java
Labels: refactor, fix

#227 Fe/fix feed back ym
  client/src/components/Header.jsx
  client/src/components/Input.jsx
  client/src/components/Message/Chat.jsx
  client/src/components/Message/MessageContent.jsx
  client/src/components/TutoringList/Tutoring.jsx
  client/src/components/modal/DefaultModal.jsx
  client/src/components/profileSection/MyProfileCard.jsx
  client/src/components/profileSection/MyProfileCard.module.css
  client/src/components/profileSection/ProfileCard.jsx
  client/src/components/profileSection/ProfileCard.module.css
  client/src/pages/Message.jsx
  client/src/pages/TuteeList.jsx
  client/src/pages/TuteeList.module.css
Labels: fix

#226 Fe/fix mk
  client/src/App.jsx
  client/src/assets/arrowDrop.png
  client/src/components/ChangeProfile/ChangeProfileContents.module.css
  client/src/components/ChangeProfile/TuteeContents.jsx
  client/src/components/ChangeProfile/TutorContents.jsx
  client/src/components/MainSection/LoginForm.jsx
  client/src/components/MainSection/SignUpForm.jsx
  client/src/components/modal/DefaultModal.jsx
  client/src/components/modal/RedModals.jsx
  client/src/components/profileSection/MyProfileCard.jsx
  client/src/pages/Error.jsx
  client/src/pages/Error.module.css
Labels: fix

#228 fix: client issue troubleshooting
  client/src/App.css
  client/src/App.jsx
  client/src/components/ChangeProfile/ChangeProfileCard.jsx
  client/src/components/ChangeProfile/ChangeProfileCard.module.css
  client/src/components/Footer.module.css
  client/src/components/Header.jsx
  client/src/components/JournalSection/JournalForm.jsx
  client/src/components/MainSection/FilterDropdown.jsx
  client/src/components/MainSection/LoginForm.jsx
  client/src/components/MainSection/UserInfoForm.jsx
  client/src/components/Message/Chat.jsx
  client/src/components/Message/Chat.module.css
  client/src/components/Message/MessageContent.jsx
  client/src/components/Message/MessageContent.module.css
  client/src/components/Message/MessageList.jsx
  client/src/components/Message/MessageList.module.css
  client/src/components/Tutoring/FinishedJournalList.jsx
  client/src/components/Tutoring/JournalList.jsx
  client/src/components/Tutoring/Journals.jsx
  client/src/components/modal/AdminModal.jsx
  client/src/components/modal/AdminModal.module.css
  client/src/components/profileSection/MyProfileCard.jsx
  client/src/components/profileSection/ProfileCard.jsx
  client/src/components/profileSection/Toggle.jsx
  client/src/components/profileSection/TutorContents.jsx
  client/src/pages/Admin.jsx
  client/src/pages/Admin.module.css
  client/src/pages/ChangeJournal.module.css
  client/src/pages/ChangeProfile.module.css
  client/src/pages/Journal.module.css
  client/src/pages/Login.module.css
  client/src/pages/Message.jsx
  client/src/pages/Message.module.css
  client/src/pages/MyProfile.jsx
  client/src/pages/MyProfile.module.css
  client/src/pages/OAuth.jsx
  client/src/pages/SignUp.module.css
  client/src/pages/TuteeList.jsx
  client/src/pages/TuteeList.module.css
  client/src/pages/TuteeProfile.jsx
  client/src/pages/TuteeProfile.module.css
  client/src/pages/TutorList.jsx
  client/src/pages/TutorList.module.css
  client/src/pages/TutorProfile.module.css
  client/src/pages/Tutoring.module.css
  client/src/pages/TutoringList.jsx
  client/src/pages/TutoringList.module.css
  client/src/pages/UserInfo.module.css
  client/src/util/Pagination.jsx
  client/src/util/Pagination.module.css
  client/src/util/validation.js
Labels: fix

#229 refactor: 소셜 로그인 후 Redirect URL 수정 - 서비스 Url 변경
  server/src/main/java/com/mainproject/server/auth/oauth2/OAuth2UserSuccessHandler.java
Labels: fix

#231 Be: 프로필 삭제 시 DB 데이터 삭제하지 않고 비활성화 상태값 수정으로 로직 변경
  server/src/main/java/com/mainproject/server/config/SecurityConfig.java
  server/src/main/java/com/mainproject/server/constant/ProfileStatus.java
  server/src/main/java/com/mainproject/server/profile/controller/ProfileController.java
  server/src/main/java/com/mainproject/server/profile/service/ProfileService.java
Labels: refactor

#232 test: 프로필 서비스 로직 변경사항 테스트 코드 반영
  server/src/test/java/com/mainproject/server/profile/service/ProfileServiceTest.java
Labels: refactor

#233 chore: Redis Endpoint 변경
  server/src/main/java/com/mainproject/server/config/RedisConfig.java
Labels: fix

#235 chore: HTTPS 인증서 적용 및 OAuth2 BaseURL 변경
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/mainproject/server/auth/oauth2/provider/CustomOAuth2Provider.java
Labels: fix

#238 Fe/fix qa mk
  client/src/components/JournalSection/EditJournalForm.jsx
  client/src/components/JournalSection/JournalForm.jsx
  client/src/components/JournalSection/JournalForm.module.css
  client/src/components/MainSection/FeedItem.module.css
  client/src/components/Tutoring/FinishedJournalList.module.css
  client/src/components/Tutoring/JournalList.module.css
  client/src/components/modal/ReviewDetail.module.css
  client/src/components/profileSection/ProfileContents.module.css
  client/src/pages/TuteeList.module.css
  client/src/pages/TutorList.module.css
Labels: refactor, fix

#239 Fe/fix qa mk
  client/src/components/MainSection/FeedItem.module.css
  client/src/components/Subject.module.css
  client/src/pages/TuteeList.module.css
  client/src/pages/TutorList.module.css
Labels: refactor, fix

#242 design: header 모바일 뷰 수정 #236
  client/src/components/Header.jsx
  client/src/components/Header.module.css
Labels: fix

#248 !HOTFIX: Tutor 프로필 검색 시 sort 값의 정렬 기준 미설정
  server/src/main/java/com/mainproject/server/profile/service/ProfileService.java
Labels: fix

#249 !HOTFIX: Tutor 프로필 검색 시 sort 값의 정렬 기준 미설정 추가 수정
  server/src/main/java/com/mainproject/server/profile/service/ProfileService.java
Labels: fix
